### ISSUE TITLE
java.lang.NoClassDefFoundError: sun/misc/BASE64Decoder

### ISSUE THREAD

**Issue by SuperGod110** [HiCoinCom/java-sdk#2]
jdk8之后的版本不存在了 能否支持下jdk高版本  我当前用的jdk11
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/17241678/202377221-8d8febac-5ca6-4e7a-adbb-e6e6794ac471.png">

**Comment by zhp1254** [comment]
fixed
